### ISSUE TITLE
[Question] Is it possible to create a xbind wrapper for applications?

### ISSUE THREAD

**Issue by alpominth** [koro666/xsocket#2]
I would like to use libxbind.so with some programs but I can't, because Go programs doesn't work with LD_PRELOAD trick.

Is it possible to create an applications wrapper that can work with these kind of executables and also static ones? Something like <ip netns exec foo>

**Comment by koro666** [comment]
It could be doable with a heavy-handed approach like `ptrace` to intercept the `socket` system call and handle it out-of-process, but I think such an approach would tank performance.

[proot](https://github.com/termux/proot/) already implements this approach in a generic way, and would likely be possible to modify its [`socket` system call handling](https://github.com/termux/proot/blob/master/src/syscall/socket.c) to call `xsocket` and swap the file descriptor.

However, at this point, it seems simpler to just recompile the static binary instead.

**Comment by alpominth** [comment]
@koro666 

ptrace is the first thing that comes to my mind in this case.

I've seen a project that implements remapping of ports using ptrace(): https://github.com/mildred/force-bind-seccomp

>However, at this point, it seems simpler to just recompile the static binary instead.

I understand, however Go compiled programs, even dynamically compiled, doesn't work with LD_PRELOAD. The lists of applications and tools that are written in Go is extensive.

I'm just using xsocket with Tor, works magically.

---

Thanks.

**Comment by alpominth** [comment]
@koro666 

`"Upon reception of such a message, the server creates the requested socket, then passes it back using SCM_RIGHTS to the client. In case of failure, an error code is returned instead."`

Just for curiosity, is it possible to do the opposite of what xsocket does actually? I mean, to listen in a namespace and connect to the network of another one instead of just listen.

If it is possible, a very good idea is to implement this feature, it would rocks.

**Comment by koro666** [comment]
> I understand, however Go compiled programs, even dynamically compiled, doesn't work with LD_PRELOAD. The lists of applications and tools that are written in Go is extensive.

The xsocket protocol is [simple enough](https://github.com/koro666/xsocket/blob/master/protocol.h) that a pure Go client could easily be written. It's basically just marshalling the `socket` parameters and getting the file descriptor or `errno` back.

> I'm just using xsocket with Tor, works magically.

Just remember that there is no security. Hopefully you are using xsocket to bind the Tor SOCKS port inside an empty namespace, and not the opposite. Otherwise, anything from inside the namespace could just create a socket and connect out.

> Just for curiosity, is it possible to do the opposite of what xsocket does actually? I mean, to listen in a namespace and connect to the network of another one instead of just listen.

It's already possible to connect out using a socket returned by xsocket. You can link with `libxsocket.so` and call `xsocket` inside. There is not just no `LD_PRELOAD` wrapper provided because I don't see the point: if you want to connect out from another namespace, then there is not much point in being in a separate namespace to begin with.

**Comment by alpominth** [comment]
@koro666 

>There is not just no LD_PRELOAD wrapper provided because I don't see the point: if you want to connect out from another namespace, then there is not much point in being in a separate namespace to begin with.

I think that implementing an option to send the outgoing connection to the netns in which xsocket-server is active is a good idea.

Some use cases:

- Run Tor in an isolated netns, Tor listen in the local addresses of the netns and send its outgoing connection to the host network, a transparent proxy is configured in the netns for a better leak protection.
- Allow the directory in which xsocket-server is listening in a unix socket to be reachable inside Docker or LXC, and configure a DNS forwarder to send the DNS queries over the host network, providing DNS to the container.
- A netns with a VPN connection is configured, xsocket-server is listening with an unix socket in the netns, a SOCKS5 server send its outgoing connection over the VPN netns and listen its ports on the host side, so providing a SOCKS5 proxy for the applications running in the host network side.

The option could be: XCONNECT=0|1

Like this: `LD_PRELOAD="/path/to/libxbind.so /path/to/libxsocket.so" XBIND="1080 3128" XCONNECT="1" XSOCKET="/tmp/foo" /usr/local/bin/proxy_server <args>`

**Comment by alpominth** [comment]
@koro666 

>Just remember that there is no security.

Maybe implementing password protection in the unix socket of xsocket-server could address the issue.

**Comment by koro666** [comment]
> I think that implementing an option to send the outgoing connection to the netns in which xsocket-server is active is a good idea.

I've recently come across a use-case where having had such a feature would have saved me some time, so I'll consider the option. However, this would need a great deal of refactoring to do it right, so I'll do this... eventually.

For my particular issue, I managed to "turn it around" by telling `curl` to explicitly bind before connecting:

```
LD_PRELOAD=libxbind.so XBIND=1234 curl --local-port 1234 https://...
```

> Maybe implementing password protection in the unix socket of xsocket-server could address the issue.

Security is hard to get right, which is why I did not want to implement any.
If I implement security and there is a flaw, then it's my fault.

> A netns with a VPN connection is configured, xsocket-server is listening with an unix socket in the netns, a SOCKS5 server send its outgoing connection over the VPN netns and listen its ports on the host side, so providing a SOCKS5 proxy for the applications running in the host network side.

This particular use case could be done by having the SOCKS5 proxy run inside the netns, and using xbind to bind its SOCKS5 port in the main namespace.

**Comment by alpominth** [comment]
>I've recently come across a use-case where having had such a feature would have saved me some time, so I'll consider the option. However, this would need a great deal of refactoring to do it right, so I'll do this... eventually.

>For my particular issue, I managed to "turn it around" by telling curl to explicitly bind before connecting:

>LD_PRELOAD=libxbind.so XBIND=1234 curl --local-port 1234 https://...

It's could be done by intercepting connect() syscall after the socket closing in the actual netns and re-opening a socket in the target netns, and so letting the connect() flow in the targert netns.

You could create a library called `"libxconnect"` apart from `libxbind`, it would work with `xsocket-server`. I think it wouldn't require refactoring the stuff.

I tested the curl trick you posted, but I couldn't make Tor and 3proxy (SOCKS5 server) work with it.

>Security is hard to get right, which is why I did not want to implement any.
>If I implement security and there is a flaw, then it's my fault.

I understand.

>This particular use case could be done by having the SOCKS5 proxy run inside the netns, and using xbind to bind its SOCKS5 port in the main namespace.

I know this works, but I said that because the majority of SOCKS servers doesn't work with `libxbind` when using UDP, that is because of a particularity of most SOCKS5 servers, the SOCKS5 servers open UDP ports dynamically, it could be any port number, and `libxbind`  doesn't intercept them:

See this thread of my friend: https://github.com/3proxy/3proxy/issues/1044#issuecomment-2178270085

**Comment by alpominth** [comment]
I tried to make a LD_PRELOAD library that opens a null port for a process, just for see if it would work together with `libxbind.so` and `xsocket-server`: https://paste.debian.net/plain/1321858

It doesn't work:

```
# LD_PRELOAD="/tmp/port_spawner.so /opt/xsocket/libxsocket.so /opt/xsocket/libxbind.so" XBIND="1111" XSOCKET="/dev/shm/foo" LADDR="127.0.0.1" LPORT="1111" curl http://1.1.1.1:80
Listening on 127.0.0.1:1111
curl: (7) Failed to connect to 1.1.1.1 port 80 after 0 ms: Couldn't connect to server
```

```
# /opt/xsocket/xsocket-server /dev/shm/foo
socket request: domain=2, type=1, protocol=6, pid=156878, uid=0, gid=0
```

At least xsocket-server receives the connection.

**Comment by koro666** [comment]
> It's could be done by intercepting connect() syscall after the socket closing in the actual netns and re-opening a socket in the target netns, and so letting the connect() flow in the targert netns.
> 
> You could create a library called `"libxconnect"` apart from `libxbind`, it would work with `xsocket-server`. I think it wouldn't require refactoring the stuff.

That is exactly what I want to do. However there is the `setsockopt` interception in `libxbind.so` which would need to be shared between the two. That, and maybe some of the initialization / socket switching code.

> I understand.

To add on to that, what I want to avoid is implementing complex allow/deny rules, because I feel that's that POSIX ACLs and firewall rules can do a better job at it than I would. However, having a simple (optional) "authkey" system might be a good idea after careful thinking. I think `xauth` operates similarly, so I'll consider adding it.

> I know this works, but I said that because the majority of SOCKS servers doesn't work with `libxbind` when using UDP, that is because of a particularity of most SOCKS5 servers, the SOCKS5 servers open UDP ports dynamically, it could be any port number, and `libxbind` doesn't intercept them:

You can use `XBIND=*` to intercept _all_ port binds. Maybe that can help.

Anyway, I'll give it a try to start implementing `xconnect` tonight, and see where that goes.

**Comment by koro666** [comment]
I have a crude version working in the `xconnect` branch if you want to play with it.

For now I am not satisfied with its overall architecture, as the `setsockopt` logic is duplicated between the libraries, and the `connect` hook ends up being called recursively. So it will stay there until I figure out what to do with it.

**Comment by alpominth** [comment]
>I have a crude version working in the xconnect branch if you want to play with it.
>For now I am not satisfied with its overall architecture, as the setsockopt logic is duplicated between the libraries, and the connect hook ends up being called recursively. So it will stay there until I figure out what to do with it.

Thanks a lot @koro666 

I'm already using it.

I'm not a experienced C or Rust programmer, but I'm studying and learning day by day to someday create a ptrace() wrapper for xsocket, and also to create my "personal" xsocket for using in production. Honestly, xsocket is one of best Githup repos.

**Comment by alpominth** [comment]
I have been testing libxconnect in that branch and I noticed that UDP doesn't work with it:

You may confirm with:

`LD_PRELOAD="/opt/xsocket/libxsocket.so /opt/xsocket/libxconnect.so" XCONNECT="*" XSOCKET="/dev/shm/blah" nc -z -u 1.1.1.1 53`

**Comment by alpominth** [comment]
I came across a little problem here when implementing xconnect in my stuff. When a program binds to an address to send outgoing traffic before connecting, it doesn't work when invoked from other network namespaces:

```
ip netns exec nsx sudo -u user LD_PRELOAD="/opt/xsocket/libxconnect.so" XCONNECT="*" XSOCKET=/tmp/sock tor -f /opt/tmp/tor-test/tor-test.torrc
Jul 04 19:01:31.371 [notice] Tor 0.4.8.12 running on Linux with Libevent 2.1.12-stable, OpenSSL 3.2.2, Zlib 1.3.1, Liblzma 5.6.2, Libzstd 1.5.6 and Glibc 2.38 as libc.
Jul 04 19:01:31.371 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
Jul 04 19:01:31.371 [notice] Read configuration file "/opt/tmp/tor-test/tor-test.torrc".
Jul 04 19:01:31.373 [notice] Opening Socks listener on 127.0.0.1:8001
Jul 04 19:01:31.373 [notice] Opened Socks listener connection (ready) on 127.0.0.1:8001
Jul 04 19:01:31.000 [notice] Parsing GEOIP IPv4 file /usr/share/tor/geoip.
Jul 04 19:01:31.000 [notice] Parsing GEOIP IPv6 file /usr/share/tor/geoip6.
Jul 04 19:01:32.000 [notice] Bootstrapped 0% (starting): Starting
Jul 04 19:01:32.000 [notice] Starting with guard context "default"
Jul 04 19:01:34.000 [warn] Error binding network socket: Cannot assign requested address
Jul 04 19:01:34.000 [warn] Error binding network socket: Cannot assign requested address
Jul 04 19:01:35.000 [warn] Error binding network socket: Cannot assign requested address
Jul 04 19:01:36.000 [warn] Error binding network socket: Cannot assign requested address
Jul 04 19:01:36.000 [warn] Error binding network socket: Cannot assign requested address
Jul 04 19:01:37.000 [warn] Error binding network socket: Cannot assign requested address
Jul 04 19:01:37.000 [warn] Error binding network socket: Cannot assign requested address
Jul 04 19:01:38.000 [warn] Error binding network socket: Cannot assign requested address
Jul 04 19:01:38.000 [warn] Error binding network socket: Cannot assign requested address
```

I tried to LD_PRELOAD the `xsocket-server` with this tool: https://github.com/meebey/force_bind

But it doesn't work, `xsocket-server` connects fine, but not using the bind address specified in the LD_PRELOAD library.

**Comment by alpominth** [comment]
**libxconnect.so** could handle `sendto` and `sendmsg` as it worked with TCP only, SCTP not tested.

**Comment by alpominth** [comment]
Sorry for creating too many replies here, but I have a suggestion for implementing in the **LD_PRELOAD** libraries of this project: an option for excluding ports when doing wildcard selection.

An use case

```
/opt/xsocket/xsocket-server /tmp/socket

export LD_PRELOAD="/opt/xsocket/libxbind.so" XBIND="*" XSOCKET="/tmp/socket"

 ip netns exec somens bash -c "LD_PRELOAD=\"/opt/xsocket/libxbind.so\" XBIND=\"*\" XSOCKET=\"/tmp/socket\"  \
  /usr/local/bin/tor Socks5Port 127.0.0.1:9050 DNSPort 127.0.0.1:9053 OutboundBindAddress 0.0.0.0 \
  OutboundBindAddress [::] User dude
```

The example above is valid, Tor will send to `xsocket-server` the bind() command specified with _OutboundBindAddress_ and `xsocket-server` will bind it to the default route of host netns. But what if the ports 9050 and 9053 are meant to listen in the netns in which **Tor** was invoked?

An option to exclude certain ports when using wildcard selection is a good idea, something like this: `export XBIND="* !9050 !9053"`

So that, ports 9050 and 9053 will be allowed to listen in the netns in which the app was invoked.

**Comment by koro666** [comment]
> **libxconnect.so** could handle `sendto` and `sendmsg` as it worked with TCP only, SCTP not tested.

Now I'm reminded as to why I didn't want to handle the connect scenario.

It's much more complex than the "application creates sockets, binds once, and goes on" case.

In particular,  how would such call interceptions even work? Should it replace the file descriptor everytime? The switch operation is already racy and risky, and is only "safe" to do when binding due to the fact that most applications bind once at startup and are done. Keeping track of "has this descriptor been swapped yet?" involves a lot of bookkeeping (and synchronization!), and requires hooking `close` as well. So now we're hooking a bunch of "trivial" system calls and doing complex logic on every call.

> An option to exclude certain ports when using wildcard selection is a good idea, something like this: `export XBIND="* !9050 !9053"`

Looks like _some_ of the refactoring I did for `xconnect` would not be wasted after all.

Since I properly extracted the "make me a port list from a string" code, adding more complexity to that parser could be done.

**Comment by alpominth** [comment]
>Now I'm reminded as to why I didn't want to handle the connect scenario.
>It's much more complex than the "application creates sockets, binds once, and goes on" case.

You're right, if you wish you can delete the xconnect branch, I found another way to make my stuff work with xsocket.

And applications can bind to address(es) before sending connect(), it would be a pain in the neck to have a single library that only handles connect(), since is just forcing the app to bind to 0.0.0.0:0/[::]/0 and sending over xsocket-server to do the same (and better).

>Looks like some of the refactoring I did for xconnect would not be wasted after all.
>Since I properly extracted the "make me a port list from a string" code, adding more complexity to that parser could be done.

I was thinking I didn't have asked you to create libxconnect.so, at least you can benefit what was implemented if you want to make the things more complex.

libxbind.so is more than enough as now I understand socket programming a little more.

The way I found to make xsocket work well with both TCP/UDP is by using it together with [forceIP](https://github.com/tool-maker/forceIP) (similar to that [force_bind](https://github.com/meebey/force_bind), but it doesn't cause segfaults in some apps):

```
LD_PRELOAD="./libxbind.so ./forceIP.so" XBIND="*" XSOCKET="/tmp/socket" fIP_BINDADDR="0.0.0.0" fIP_BINDADDR6="::"
  /usr/local/bin/tor <args>
```

forceIP will force the app to bind to host network and will send this command to xsocket-server, and the rest you know. But the issue is if the program is intended to spawn listening port in the netns in which it was invoked, using wildcard (*) will make it listen in the host space.

`XBIND="* !<port1> !<port2>"` is the solution.

**Comment by alpominth** [comment]
Another suggestion:

You could refactor the LD_PRELOAD libraries to accept IP addresses together with ports, like this:

XBIND="127.0.0.1:1080 10.0.0.1:* *:3128"

IMO is more flexible to use, even more if combined with wildcard (*), and it's fine to change the syntax of `XBIND` env, I think there are only 3 people using this project.

**Comment by alpominth** [comment]
>Now I'm reminded as to why I didn't want to handle the connect scenario.
>It's much more complex than the "application creates sockets, binds once, and goes on" case.

You're right, but it's only **send()**, **sendto**, **sendmsg** and **sendmmsg** for UDP and other similar protocols to work 100%:

https://man7.org/linux/man-pages/man2/sendto.2.html
https://man7.org/linux/man-pages/man2/sendmmsg.2.html

Could you, at your time, implement this?

The rest you can implement in the future. The reason why you cannot replace `libxconnect` with `libxbind` is that the program should be forced to bind to an address before connecting for working with `libxbind`, the most used **connect()** operations doesn't bind to an specific address but **0.0.0.0/[::]**. In my tests, I cannot pass **0.0.0.0/[::]** to `libxbind` to make bind in another netns.

I suggest you to not give up of `libxconnect`.

>Looks like some of the refactoring I did for xconnect would not be wasted after all.
>Since I properly extracted the "make me a port list from a string" code, adding more complexity to that parser could be done.

I was thinking I didn't have asked you to create `libxconnect.so`, at least you can benefit what was implemented if you want to make the things more complex. But I changed my mind after facing issues when implementing `xsocket` in my stuff, `libxconnect` is as useful as `libxbind`, IMO.

---

Well, my suggestion for allowing ports to be excluded when doing wildcard selection of ports I made:

`XBIND="* !<port1> !<port2>"`

If you could implement, at your time, I would appreciate very much.

I have another suggestion:

You could refactor the `LD_PRELOAD` libraries (`libxbind` and `libxconnect`) to accept IP addresses together with ports, like this:

`XBIND="127.0.0.1:1080 10.0.0.1:* *:3128"`

IMO is more flexible to use, even more if combined with wildcard (*), and it's fine to change the syntax of `XBIND`/`XCONNNECT` envs, I guess there are only 3 people using this project.

---

Sorry for asking too much, but I'm facing some issues when including in my stuff (LXC, Docker, shell scripts, Firejail and others), for example, UDP **sendto**/**sendmsg** issue and port exclusion in wildcards.

PS.: I have had to delete the previous posts here because I made a mess, and I realized about the impossibility of passing **0.0.0.0/[::]** to `libxbind`, I was thinking I could replace `libxconnect` with `libxbind` (I can't).

**Comment by alpominth** [comment]
send() already works with libxconnect (I was wrong) as a connect() syscall must precede it, that's why UDP work for some programs like `$ host`.

But sendto() can be implemented by grabbing it and filling it with destination data:

```
       ssize_t sendto(int sockfd, const void buf[.len], size_t len, int flags,
                      const struct sockaddr *dest_addr, socklen_t addrlen);
```

If a connect() one precede sendto(), there is nothing to hack around.

Connectionless protocols could use sendmsg() and sendmmsg(), if they are preceded by a connect() is fine, they will work with libxconnect, but if not, implementing it wouldn't be so trick IMO, all I one can do is to look at `strcut mmsghdr` in `<sys/socket.h>` and `<bits/socket.h>`

```
/* Structure describing messages sent by
   `sendmsg' and received by `recvmsg'.  */
struct msghdr
  {
    void *msg_name;		/* Address to send to/receive from.  */
    socklen_t msg_namelen;	/* Length of address data.  */

    struct iovec *msg_iov;	/* Vector of data to send/receive into.  */
    size_t msg_iovlen;		/* Number of elements in the vector.  */

    void *msg_control;		/* Ancillary data (eg BSD filedesc passing). */
    size_t msg_controllen;	/* Ancillary data buffer length.
				   !! The type should be socklen_t but the
				   definition of the kernel is incompatible
				   with this.  */

    int msg_flags;		/* Flags on received message.  */
  };
```

Really, libxconnect with support for sendto(), sendmsg() and sendmmsg() would rocks and put xsocket project in another level.

I'm standing on my ignorance in C, but I'm learning day by day, I'm trying to create a prototype of a parser for `<IP>:<PORT>` in the preload libraries.

**Comment by alpominth** [comment]
I'm closing this topic as my question was answered.

@koro666 

I have written a support material for the case you decide to continue with **xconnect** branch: [syscall_test.tar.gz](https://github.com/user-attachments/files/16517253/syscall_test.tar.gz)

The syscalls related with UDP and other protocols are: `sendto()`, `sendmsg()`, `sendmmsg()`, `write()` and `writev()`.

`send()` already works with UDP because a `connect()` syscall must precede it.

For making them work with **xconnect** is only checking if they are not preceded by a `connect()` syscall, for `write()` and `writev()` check also if the FD is a socket, if not preceded by connect() is just processing them as connect() to make them work partially, perhaps the hard work would be modifying **xconnect** branch or maybe refactoring some stuff.

Have a nice day.

**Comment by alpominth** [comment]
@koro666 

Any plan to implement sendto(), sendmsg(), sendmmsg(), write() and writev() in libxconnect branch soon?

Sorry for asking too much, but I'm really in need of this.

**Comment by koro666** [comment]
I will implement improved port filtering next time I touch the code, but I don't intend on implementing the rest, that's way too invasive.

**Comment by alpominth** [comment]
I understand @koro666 .

Changing the subject, this repository doesn't have a proper License, is it placed on public domain?

**Comment by koro666** [comment]
The license is: do whatever you want with it, as long as it's not commercial.

**Comment by alpominth** [comment]
I'm so sorry if I'm sounding annoying by saying about sendto()/sendmsg()/sendmmsg() again, but...

I'm using xsocket in production and I'm having fun, but 50% of other use cases xsocket is useless for my needs, more precisely for DNS forwarding and SOCKS5 proxies. I'm trying to forward DNS traffic from host network to a Docker container and I can't because the few UDP port forwarders in Github use sendto()/sendmsg()/sendmmsg(), connect() works mostly for TCP. Another problem is SOCKS5 proxies inside LXC, I can make them work inside LXC but partialy, because UDP Associate of these proxies relies on sendto()/sendmsg()/sendmmsg(), and there is no solution that makes them use connect.

I really believe that sendto()/sendmsg()/sendmmsg() support in xconnect branch can make xsocket a full featured socket handler solution for Linux. There is another approaches like [socketat](https://github.com/aojea/socketat), but it requires root for setns() and requires unsandboxed usage.

I recommend that you implement sendto()/sendmsg()/sendmmsg() in xconnect branch, if you want a reward for the time spent, I can became a sponsor in the future.

Thanks and remember, my intention is not to put pressure on anyone and annoying you.

**Comment by koro666** [comment]
The primary problem with hooking libc functions is that it introduces foreign code which runs everytime one of them is being called.

Those functions are supposed to be "trivial" and [async-safe](https://man7.org/linux/man-pages/man7/signal-safety.7.html), which means they are meant to just be a thin wrapper which performs a system call which performs the operation atomically.

Already by hooking `bind`, this assumption is broken. When called, it has to:

- determine if the address that is bound to should be handled;
- create a temporary socket, connect to server;
- send request, receive response with file descriptor to replacement socket;
- close temporary socket;
- attempt to copy all socket options which may have been set using a loop of `getsockopt` and `setsockopt`;
- replace the original socket with `dup2`
- look up the original `bind` function pointer and cache it (definitely not async-safe - though it could be moved to the library constructor);
- finally forward to the original `bind` function.

That is a lot of steps (each of which may fail for a variety of reasons) for what used to be a trivial system call. Fortunately, pretty much every daemon usually does `socket`, `setsockopt`, `bind`, `listen` once during initialization, so it's "relatively safe" to just hook `bind`: once daemon initialization is done, almost none of my code ever runs again. Only `setsockopt` may be called often, and it is designed to not allocate memory and just do a few atomic writes to fixed addresses.

Hooking `connect` the same way was trivial (very similar logic), though it may get called more often. But for any of the functions taking the target address on every call, it introduces another problem: keeping track of whether the socket was replaced or not. What to do if one call specifies an address/port combination which should be handled, but the next one doesn't? What if it's two calls happening in parallel on two different threads? What if it's called from within a signal handler?

At least for `bind` (and maybe `connect`) we can assume they won't be called too often.

My primary use case for xsocket is to expose the "control port" of processes which are run in isolated network namespaces, whether it's a systemd service or LXC container. I use it to expose the Transmission RPC port, SSH/VNC ports, etc. I want to run the least amount of custom code in these contexts because a mistake or bug would have dire consequences. The simplest case would be a crash, but the worse case would be opening up a [security vulnerability](https://www.openwall.com/lists/oss-security/2024/07/01/3) or silent data corruption due to file descriptor confusion.

I already consider `libxsocket.so` and `xsocket-server` to be a hack, in that the kernel should _really_ provide a `socketat` system call the same way it provides `openat`, and not require any special capabilities to use it. Having an open file descriptor to a netns should be enough to be able to use it. On top of this, I consider `libxbind.so` to be a hack on top of a hack, just "good enough" to allow listening in another namespace without modifying the target program. But for anything more complex, it would be simpler to just add xsocket-awareness directly in the source code of whichever program needs it.

**Comment by alpominth** [comment]
Ok, I understand perfectly.

Last question: will **xconnect** branch here be developed or will be discontinued?

**Comment by koro666** [comment]
There are some good refactor commits that need to be brought back to `master` in there... next time I feel motivated to touch this project. So, I don't intend to delete it, probably will keep it rebased as a small "unofficial" add-on.

**Comment by alpominth** [comment]
>At least for bind (and maybe connect) we can assume they won't be called too often.

My intention is not to upset or pressure you, but I have to disagree with the above statement.

SOCKS5 servers that serve UDP connection can use lots of UDP ports using bind() syscall, and also UDP proxy forwarders that relies on TPROXY.

Here is the log of a local SOCKS5 server with UDP using libxbind.so in just 90 seconds of navigation into Facebook, Google, Instagram and WhatsApp web app: https://pastee.dev/p/tLay2mKx

You can see that bind() sometimes is used often.

xsocket can be seem as the best anonymity tool on Github, because you (using libxbind.so) can just adjust a proxy program to listen inside a enclosed netns and point the browser or another program to use the proxy, IP leaks wouldn't happen, even with a bug in the program that makes the IP leak, the netns doesn't having any outgoing host connectivity will act as a barrier to any IP leaks in the browser/app.

Another suggestion: you should know that some programs can bind to local IP addresses before sending outgoing connections, they bind (internally) to port zero (for example 192.168.1.3:0) and the system assigns a ephemeral port automatically, you could make libxbind.so accepts zero-ports like this, I have made some tests and I could realize that XBIND is not read if a "zero" port is passed to it.

**Comment by alpominth** [comment]
>At least for bind (and maybe connect) we can assume they won't be called too often.

My intention is not to upset you, but I have to disagree with the above statement.

SOCKS5 servers that serve UDP connection can use lots of UDP ports using bind() syscall, and also UDP proxy forwarders that relies on TPROXY.

Here is the log of a local SOCKS5 server with UDP using libxbind.so in just 90 seconds of navigation into Facebook, Google, Instagram and WhatsApp web app: https://pastee.dev/p/tLay2mKx

You can see that bind() sometimes is used often.

One suggestion: you should know that some programs can bind to local IP addresses before sending outgoing connections, they bind (internally) to port zero (for example 192.168.1.3:0) and the system assigns a ephemeral port automatically, you could make libxbind.so accepts zero-ports like this, I have made some tests and I could realize that XBIND is not read if a "zero" port is passed to it.

(I deleted my previous post because it sounded inconvenient).

**Comment by koro666** [comment]
I'm slowly working on improving filtering on my idle time.

Port ranges and negation works, next is to be able to specify addresses/netblocks.

**Comment by alpominth** [comment]
>Port ranges and negation works, next is to be able to specify addresses/netblocks.

Port wildcards would be a good idea.
